import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ChatbotService {
  private responses: { [key: string]: string } = {
    'how to bid': 'To place a bid, enter an amount higher than the current bid in the input field and click "Place Bid". Make sure you have paid the required amount first!',
    'how to pay': 'To pay, click "Pay the required amount", enter at least $50 in the popup, and confirm your payment. Once paid, you can start bidding.',
    'what is an auction': 'An auction is a process where users bid to win an item. The highest bidder wins when the auction ends.',
    'how to create an auction': 'To create an auction, go to the "Create Auction" page, fill in the details like item name, category, and end time, then submit.',
    'what happens if i win': 'If you win, you’ll be notified, and the item will be marked as yours in the "Won Auctions" section.',
    'how to check my bids': 'Go to the "Active Bids" section to see all your current bids.',
    'can i cancel a bid': 'No, bids cannot be canceled once placed. Please bid carefully!',
    'what is the minimum bid': 'The minimum bid must be higher than the current bid shown on the auction page.',
    'how to contact the seller': 'You can’t directly contact the seller, but you can reach out to support for help.',
    'what happens if auction ends': 'When the auction ends, the highest bidder wins, and the auction status changes to "Closed".',
    'how to see won auctions': 'Go to the "Won Auctions" section to see all auctions you’ve won.',
    'how to see lost auctions': 'Check the "Lost Auctions" section to see auctions you didn’t win.',
    'what is payment amount': 'The payment amount is a symbolic fee of $50 required to start bidding on an auction.',
    'can i bid on multiple auctions': 'Yes, you can bid on multiple auctions as long as you’ve paid the required amount for each.',
    'how to know auction time': 'The "Time Left" on the auction page shows how much time is remaining.',
    'what if i don’t pay': 'If you don’t pay the required amount, you won’t be able to place a bid.',
    'how to change my bid': 'You can’t change a bid, but you can place a new higher bid.',
    'what is current bid': 'The current bid is the highest bid placed on the auction so far.',
    'how to see bidding history': 'The bidding history is shown on the auction details page under "Bidding History".',
    'what is highest bid': 'The highest bid is the maximum amount bid on the auction, shown in the "Highest Bid" section.',
    'how to register': 'To register, go to the "Sign Up" page, enter your details, and submit.',
    'how to log in': 'Go to the "Login" page, enter your email and password, and click "Login".',
    'how to reset password': 'Click "Forgot Password" on the login page, enter your email, and follow the instructions.',
    'what is my user id': 'Your user ID is your email or name, depending on what you used to register.',
    'how to update profile': 'Go to "My Profile" and update your details like name or email.',
    'can i delete my account': 'Yes, contact support to delete your account.',
    'how to contact support': 'Go to the "Support" page and fill out the contact form.',
    'what are auction categories': 'Categories include electronics, fashion, art, and more. Check the auction creation page for the full list.',
    'how to search auctions': 'Use the search bar at the top of the page to find auctions by name or category.',
    'what is auction status': 'Auction status can be "Open" (active), "Closed" (ended), or "Canceled".',
    'how to cancel an auction': 'Only the seller can cancel an auction before it ends. Go to the auction details and click "Cancel".',
    'what if no one bids': 'If no one bids, the auction closes without a winner.',
    'how to extend auction time': 'Sellers can extend the auction time from the auction details page before it ends.',
    'what is bid increment': 'Bid increment is the minimum amount by which you must increase your bid over the current bid.',
    'how to set bid increment': 'Bid increment is set by the system automatically, usually $1 above the current bid.',
    'what is auction end time': 'The end time is the date and time when the auction will close, shown on the auction page.',
    'how to see auction location': 'The auction location is displayed on the auction details page.',
    'what if auction is canceled': 'If an auction is canceled, all bids are voided, and you’ll be notified.',
    'how to report a problem': 'Go to the "Support" page and submit a report with the details of the problem.',
    'what is a seller': 'A seller is the user who created the auction and is offering the item for bidding.',
    'what is a bidder': 'A bidder is a user who places a bid on an auction.',
    'how to become a seller': 'Any registered user can become a seller by creating an auction from the "Create Auction" page.',
    'what is auction image': 'The auction image is a picture of the item being auctioned, uploaded by the seller.',
    'how to upload auction image': 'When creating an auction, there’s an option to upload an image of the item.',
    'what if auction image is missing': 'If there’s no image, a placeholder image will be shown.',
    'how to delete an auction': 'Sellers can delete an auction from the auction details page if it hasn’t started yet.',
    'what is auction name': 'The auction name is the title of the auction, set by the seller.',
    'how to change auction name': 'Sellers can edit the auction name from the auction details page before it starts.',
    'what is auction description': 'The auction description provides details about the item, set by the seller.',
    'how to add auction description': 'When creating an auction, there’s a field to enter the description of the item.',
    'what if i miss the auction': 'If you miss the auction, you can look for similar items in other auctions.',
    'how to see all auctions': 'Go to the "All Auctions" page to see a list of all active auctions.',
    'what is auction filter': 'Filters let you sort auctions by category, location, or status.',
    'how to use auction filters': 'On the "All Auctions" page, use the dropdowns to filter by category or other options.',
    'what is auction sorting': 'Sorting lets you arrange auctions by end time, current bid, or name.',
    'how to sort auctions': 'On the "All Auctions" page, use the sort options to arrange the list.',
    'what is auction notification': 'Notifications alert you about auction updates, like when you’re outbid.',
    'how to enable notifications': 'Go to "Settings" and enable notifications for auction updates.',
    'what if i’m outbid': 'If you’re outbid, you’ll get a notification, and you can place a higher bid.',
    'how to see outbid auctions': 'Check the "Active Bids" section for auctions where you’ve been outbid.',
    'what is auction payment': 'Auction payment is the final amount you pay if you win the auction.',
    'how to pay for a won auction': 'Go to "Won Auctions", select the auction, and follow the payment instructions.',
    'what if i don’t pay for a won auction': 'If you don’t pay, the auction may be offered to the next highest bidder.',
    'how to track auction payment': 'Check the "Won Auctions" section for payment status.',
    'what is auction delivery': 'Delivery is how the item is sent to the winner, arranged by the seller.',
    'how to arrange auction delivery': 'Contact the seller through the platform to arrange delivery after winning.',
    'what if delivery is late': 'Contact the seller or support if the delivery is delayed.',
    'how to rate a seller': 'After receiving the item, you can rate the seller from the "Won Auctions" page.',
    'what is seller rating': 'Seller rating is a score given by bidders based on their experience.',
    'how to see seller rating': 'Seller ratings are shown on the seller’s profile page.',
    'what is bidder rating': 'Bidder rating is a score given by sellers based on your bidding behavior.',
    'how to see bidder rating': 'Check your profile to see your bidder rating.',
    'what if i get a bad rating': 'You can contact support to appeal a bad rating if you believe it’s unfair.',
    'how to improve my rating': 'Be honest, pay on time, and communicate well to improve your rating.',
    'what is auction dispute': 'A dispute happens if there’s a problem with the auction, like a fake item.',
    'how to file a dispute': 'Go to "Support" and file a dispute with details of the issue.',
    'what happens in a dispute': 'Support will investigate the dispute and decide on a resolution.',
    'how to avoid disputes': 'Read the auction description carefully and communicate with the seller.',
    'what is auction fee': 'Some auctions may have a fee, like the $50 symbolic payment to bid.',
    'how to know auction fees': 'Fees are shown on the auction page before you bid.',
    'what if i can’t bid': 'If you can’t bid, check if you’ve paid the required amount or if the auction has ended.',
    'how to see auction winners': 'Winners are shown on the auction details page after the auction ends.',
    'what is auction start time': 'The start time is when the auction opens for bidding, set by the seller.',
    'how to know auction start time': 'The start time is shown on the auction details page.',
    'what if auction doesn’t start': 'If an auction doesn’t start, it may have been canceled by the seller.',
    'how to share an auction': 'Use the "Share" button on the auction page to share it with others.',
    'what is auction privacy': 'Auction privacy settings determine who can see or bid on the auction.',
    'how to set auction privacy': 'Sellers can set privacy options when creating an auction.',
    'what is a private auction': 'A private auction is only visible to invited users.',
    'how to join a private auction': 'You need an invitation from the seller to join a private auction.',
    'what is auction bid limit': 'Some auctions may have a maximum bid limit set by the seller.',
    'how to know bid limit': 'The bid limit, if any, is shown on the auction page.',
    'what if i exceed bid limit': 'If you exceed the bid limit, your bid won’t be accepted.',
    'how to see auction rules': 'Auction rules are listed on the auction details page.',
    'what are bidding rules': 'Bidding rules include paying the required amount and bidding higher than the current bid.',
    'how to follow bidding rules': 'Read the auction rules carefully before placing a bid.',
    'what is auction support': 'Auction support helps with issues like disputes or technical problems.',
    'how to get auction support': 'Go to the "Support" page and submit your issue.',
    'what if i lose internet': 'If you lose internet, your bid will still be saved if it was placed before.',
    'how to bid without internet': 'You can’t bid without internet; you need to be online.',
    'default': 'Sorry, I didn’t understand that. Please ask something like "How to bid?" or "How to pay?"'
  };

  getResponse(query: string): string {
  const cleanQuery = query.toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, '').trim();
    return this.responses[cleanQuery] || this.responses['default'];
  }
}